services:
  app:
    image: ghcr.io/jacobsky/checkpoint:latest
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.checkpointservice.rule=Host(`checkpoint.apparently-typ.ing`)"
        - "traefik.http.routers.checkpointservice.entrypoints=websecure"
        - "traefik.http.routers.checkpointservice.tls.certresolver=le"
        - "traefik.http.services.checkpointservice.loadbalancer.server.port=80"
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      DB_ADDRESS: checkpoint.db
      DB_MIGRATION_VERSION: 1
    volumes:
      - checkpoint_db:/app
volumes:
  checkpoint_db:
